# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poker_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import poker_messages_pb2 as poker__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='poker_server.proto',
  package='poker',
  syntax='proto3',
  serialized_options=b'\200\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12poker_server.proto\x12\x05poker\x1a\x14poker_messages.proto2\x9f\x02\n\x0cPokerService\x12\x33\n\tGetDealer\x12\x11.poker.PlayerData\x1a\x11.poker.PlayerData(\x01\x12\x37\n\x0fGetPlayerAction\x12\x11.poker.PlayerData\x1a\x11.poker.ActionData\x12\x35\n\x0eGetPlayerCards\x12\x11.poker.PlayerData\x1a\x10.poker.CardsData\x12;\n\rGetBoardCards\x12\x18.poker.BoardCardsRequest\x1a\x10.poker.CardsData\x12-\n\tGetBlinds\x12\x11.poker.PlayerData\x1a\r.poker.AmountB\x03\x80\x01\x01\x62\x06proto3'
  ,
  dependencies=[poker__messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_POKERSERVICE = _descriptor.ServiceDescriptor(
  name='PokerService',
  full_name='poker.PokerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=52,
  serialized_end=339,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDealer',
    full_name='poker.PokerService.GetDealer',
    index=0,
    containing_service=None,
    input_type=poker__messages__pb2._PLAYERDATA,
    output_type=poker__messages__pb2._PLAYERDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlayerAction',
    full_name='poker.PokerService.GetPlayerAction',
    index=1,
    containing_service=None,
    input_type=poker__messages__pb2._PLAYERDATA,
    output_type=poker__messages__pb2._ACTIONDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlayerCards',
    full_name='poker.PokerService.GetPlayerCards',
    index=2,
    containing_service=None,
    input_type=poker__messages__pb2._PLAYERDATA,
    output_type=poker__messages__pb2._CARDSDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBoardCards',
    full_name='poker.PokerService.GetBoardCards',
    index=3,
    containing_service=None,
    input_type=poker__messages__pb2._BOARDCARDSREQUEST,
    output_type=poker__messages__pb2._CARDSDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBlinds',
    full_name='poker.PokerService.GetBlinds',
    index=4,
    containing_service=None,
    input_type=poker__messages__pb2._PLAYERDATA,
    output_type=poker__messages__pb2._AMOUNT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POKERSERVICE)

DESCRIPTOR.services_by_name['PokerService'] = _POKERSERVICE

# @@protoc_insertion_point(module_scope)
